In [1]:
import numpy as np

In [2]:
arr = np.arange(0,101)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [3]:
arr.dtype

dtype('int64')

In [6]:
arr1 = arr
arr1.astype("float64")

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

## Downcasting to Save Memory

The core idea of downcasting is to optimize memory by reducing the bit size of an array's data type, such as converting from $\text{int64}$ (8 bytes) to $\text{int32}$ (4 bytes). This technique is crucial when a dataset's maximum value can be safely represented by a smaller type. By ensuring the data type's memory footprint is just large enough for the range of values, you can save significant memory. This reduction in memory usage directly translates into faster data loading and improved processing speeds, as more data fits into the CPU's cache. This optimization is achieved without compromising data integrity, provided no values exceed the new, smaller type's capacity.

In [9]:
arr_large = np.array([100000, 200000, 300000], dtype=np.int64)
arr_small = arr_large.astype(np.int32) # Downcastting to small
print(arr_small)
print(arr_small.dtype)

[100000 200000 300000]
int32


In [16]:
print(f"Small: {arr_small.nbytes}")
print(f"Large: {arr_large.nbytes}")

Small: 12
Large: 24
