In [1]:
import numpy as np

## Creating Array from Scratch

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((2, 12), 8)

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.arange(1, 101, 9)

array([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100])

In [12]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [17]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
arr.shape

(4, 3)

In [19]:
arr.size

12

In [20]:
arr.ndim

2

In [21]:
arr.dtype

dtype('int64')

In [24]:
n = arr.astype('float64')

In [25]:
n.dtype

dtype('float64')