In [1]:
import numpy as np

### Creating Array from Scratch

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.full((2, 12), 8)

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.arange(1, 101, 9)

array([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100])

In [7]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [8]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Check the Shape/Dimension of Matrix

In [9]:
arr.shape

(4, 3)

### Total Numbers of Element in the Matrix

In [10]:
arr.size

12

### Total Count of Dimensions

In [11]:
arr.ndim

2

### Check the Data Type for Matrix

In [12]:
arr.dtype

dtype('int64')

### Change the Data Type for Matrix

In [13]:
n = arr.astype('float64')

In [14]:
n.dtype

dtype('float64')

### Matrix Dimension

In [15]:
myarr = arr
print(myarr)
myarr.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

### Reshaped the Matrix Dimension

In [16]:
reshaped = myarr.reshape((3,4))
print(reshaped)
reshaped.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)

### Change into one dimensional array

In [17]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Index in Numpy Array

In [18]:
flat = myarr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
print(f"First element of array: {flat[0]}")

First element of array: 1


In [20]:
print(f"Third to Sixth Element: {flat[2:6]}")

Third to Sixth Element: [3 4 5 6]


In [21]:
flat[:5] #same as flat [0:5}

array([1, 2, 3, 4, 5])

In [22]:
flat[3:] #same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
flat[::2] #every second element

array([ 1,  3,  5,  7,  9, 11])

## Slicing returns a view, not a copy! Changes affect the original array. 

Slicing a NumPy array typically returns a view of the original data, not a separate copy, for reasons of efficiency and performance. This behavior is why modifications to the slice affect the original array. Both the sliced array and the original array share the same data in memory.

In [24]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
b= flat[3:7]
print(b)

[4 5 6 7]


In [26]:
b[0] = 444
print(b)

[444   5   6   7]


In [27]:
flat

array([  1,   2,   3, 444,   5,   6,   7,   8,   9,  10,  11,  12])

I have explained the concept in above example and we can clearly see it does effect the original array due to optimizing the efficiency and performance.

In [28]:
flat

array([  1,   2,   3, 444,   5,   6,   7,   8,   9,  10,  11,  12])

In [29]:
c = flat[3:7].copy() #This is not a slice, we are using copy method 
print(c)

[444   5   6   7]


In [30]:
c[0] = 5555
c

array([5555,    5,    6,    7])

In [31]:
flat

array([  1,   2,   3, 444,   5,   6,   7,   8,   9,  10,  11,  12])

You can clearly by using a copy method we explicitly told numpy to make a copy of the array and do not change the data in original string.

### Boolean Masking (Filter Data) - Faster way to filter large datasets

Why Boolean Masking Is Fast for Large Datasets?

Boolean masking is highly efficient because NumPy relies on vectorization, meaning operations like A > 20 are executed in optimized C code—not slow Python loops. Instead of checking each element one by one, NumPy processes entire chunks of data at once.

NumPy arrays also use contiguous memory, allowing faster, cache-friendly data access. You can also modify values directly using masks (e.g., A[A < 10] = 0), again without any Python loops.

Let's see the below example:

In [32]:
flat[flat>8] #Boolean Masking - we are denoting a conditions while calling out a array only the one who satisfied the conditions are called

array([444,   9,  10,  11,  12])

### Exercise for Practice
- Create a 3x3 array filled with random numbers and print it's shape.
- Covert an array of floats [1.1, 2,2, 3.3] into integer.
- Use indexing to extract even number from an array.
- Reshape a 1D array of size 9 into 3x3 matrix
- Use boolean masking to filter numbers greater than 50 in an array

## Solved Examples

In [33]:
import numpy as np

In [34]:
#Creating a 3x3 matrix filled with number (1-9)
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
#Covert data type of array 

print(arr.dtype)

new_arr = arr.astype('float64')
new_arr.dtype

int64


dtype('float64')

In [36]:
# Extract even numbers from an array

arr1 = np.arange(0,10,2)
arr1

array([0, 2, 4, 6, 8])

In [37]:
# Reshape a 1D array to 3D array

reshape_array = np.arange(1,10)
reshape_array.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
#Use boolean masking to filter number greater than 50

arr2 = np.arange(1,101) #Creating a new array
arr2 
arr2[arr2>50]

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])